[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["cd backend && python -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python app_postgresql_api.py"
